# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3f968fbb826724dd5656cbfab98337478eac2e86f7f0bb23aea8402c92df30c77450828fc3d03ac9a771737c77dca11246920470ffde83a8760d88036a92661e

test:
  secret_key_base: 6532d4e0c4062a12dd7c1e7294ff304798d59cc9972a9ea560c33b4e730f1167dd7e30fa2dfd1a49222e1414936a56ddc8fa56450cea0738b9036f18cfbe5ed2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
